### ISSUE TITLE
Wrong update information embedded in AppImage

### ISSUE THREAD

**Issue by probonopd** [appimage-packages/kmail#3]
```
me@host:~$ /home/me/Downloads/kmail-git20170206-x86_64.AppImage --appimage-updateinformation
zsync|kmail-git20170206-x86_64.AppImage
```

This is not going to work, AppImageUpdate has no way of knowing where to download the zsync file from. As per the [spec](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#zsync-1), it needs to be:

```
zsync|https://s3.eu-central-1.amazonaws.com/ds9-apps/kmail-master-appimage/kmail_latestversion.zsync
```

**Comment by ScarlettGatelyMoore** [comment]
I see where I went wrong. commiting fix.

**Comment by probonopd** [comment]
```
$ /home/me/Downloads/kmail-git20170208-x86_64.AppImage --appimage-updateinformation
 zsync|https://s3-eu-central-1.amazonaws.com/ds9-apps/kmail-appimage/master/kmail-git20170208-x86_64.AppImage
```
ends in `.AppImage` and not (as it should) in `.AppImage.zsync; looks like the `appimagetool -u` argument was missing the ".zsync" at the end.

**Comment by probonopd** [comment]
With https://s3-eu-central-1.amazonaws.com/ds9-apps/kmail-master-appimage/kmail-git20170211-x86_64.AppImage, this is in the Update Information: https://s3-eu-central-1.amazonaws.com/ds9-apps/kmail-appimage/master/kmail_latestversion.zsync but a file with this name does not exist on the server...

**Comment by ScarlettGatelyMoore** [comment]
ok paths fixed now. still not updating :(

**Comment by probonopd** [comment]
In the last version, the correct paths are in. Running into https://github.com/probonopd/zsync-curl/issues/17 now. Not specifically related to this AppImage, which most likely is fine.

**Comment by probonopd** [comment]
Good news, identified the root cause of the remaining issue, https://github.com/probonopd/zsync-curl/issues/17

**Comment by probonopd** [comment]
[AppImageUpdate](https://bintray.com/probono/AppImages/AppImageUpdate/) version 443 and later _should_ be able to download from S3 now, because they are using the _semistatic_ build of `zsync-curl` (that links to libcurl statically but to OpenSSL dynamically).

```
wget -c "https://s3.eu-central-1.amazonaws.com/ds9-apps/kmail-master-appimage/kmail-git20170214-13:41:28-x86_64.AppImage"
./AppImageUpdate-443.g69bf471-x86_64.AppImage /home/me/kmail-git20170214-13\:41\:28-x86_64.AppImage 
```

Works for me: File is delta-updated, 98.1% are reused from the old version and only 1.9% are downloaded.

Please reports how it works for you.

**Comment by ScarlettGatelyMoore** [comment]
This is now fixed. Thanks!
