### ISSUE TITLE
Plugin library 'grantlee_defaulttags' not found.

### ISSUE THREAD

**Issue by probonopd** [appimage-packages/kmail#8]
`kmail-git20170217-19:19:20-x86_64.AppImage` on Ubuntu 16.04, if I make a new draft mail and then want to view it, it says "Plugin library 'grantlee_defaulttags' not found."

**Comment by probonopd** [comment]
I did this for the [Subsurface AppImage](https://github.com/probonopd/AppImages/blob/master/recipes/subsurface/Recipe) which also uses grantlee:

```
# According to http://www.grantlee.org/apidox/using_and_deploying.html
# Grantlee looks for plugins in $QT_PLUGIN_DIR/grantlee/$grantleeversion/
mv ./usr/lib/grantlee/ ./usr/lib/qt5/plugins/
```

**Comment by probonopd** [comment]
Still getting `grantlee.template: "Plugin library 'grantlee_defaulttags' not found."` in 
[kmail-git20170217-22_54_21-x86_64.AppImage](https://s3-eu-central-1.amazonaws.com/ds9-apps/kmail-master-appimage/kmail-git20170217-22:54:21-x86_64.AppImage).

**Comment by ScarlettGatelyMoore** [comment]
Yep, very much aware. Been fighting with it for days. I think I finally found the answer... in some old thread it is mentioned CMAKE_BUILD_TYPE must match grantlee and QT. So I am rebuilding the docker image and bumping qt to 5.8 while I am at it. This won't finish for many hours.

**Comment by probonopd** [comment]
Interesting, keeping fingers crossed.

**Comment by ScarlettGatelyMoore** [comment]
Did nothing. Still trying..

**Comment by ScarlettGatelyMoore** [comment]
Please test https://s3-eu-central-1.amazonaws.com/ds9-apps/kmail-master-appimage/kmail-git20170221-18:02:00-x86_64.AppImage

@probonopd @star-buck

**Comment by star-buck** [comment]
still get akonadi not running.

**Comment by probonopd** [comment]
Let's find out what KMail does when you press the start button, and let's do the exact same thing from the bash script.

**Comment by ScarlettGatelyMoore** [comment]
This specific issue is fixed. Now sorting out https://github.com/appimage-packages/kmail/issues/10
