### ISSUE TITLE
Could not start the account wizard

### ISSUE THREAD

**Issue by probonopd** [appimage-packages/kmail#9]
On Ubuntu 16.04:

```
# !!! ATTTENTION !!! Know what you are doing
# THIS WILL DELETE ALL YOUR MAIL, only run on a test system
$ rm -rf /home/me/.kmail2/
$ rm -rf ./.config/kmail*
$ rm -rf ./.local/share/kmail2
$ rm -rf ./.kmail2
```
and then launching KMail gets me

> Could not start the account wizard. Please make sure you have AccountWizard properly installed.

**Comment by ScarlettGatelyMoore** [comment]
This is now fixed, I had no idea accountwizard was it's own repo..

**Comment by probonopd** [comment]
Works for me now, thanks.
